LXI H,1000H ; TAKE USER DATA AT 1000H AND STORE IN H (USER BASED INPUT)
MOV A,M ; CONTENT OF MEMORY IS STORED IN ACCUMULATOR
INX H ; H++ INCREMENT OF ADDRESS
ADD M ; A=A+M
STA 1002H  ;STORE AT AN ADDRESS
HALT ;
